added future readme
Tompoudurans/data-explore pull request #5
Opened 2020-07-14 08:46 UTC by Tompoudurans

this is the readme put in Issue https://github.com/Tompoudurans/data-explore/issues/1 thought the code does not has all of it features yet

2020-08-11 14:32 UTC, drvinceknight commented
> this is the readme put in Issue #1 thought the code does not has all of it features yet

The README looks fine but I'd cherry pick this commit to the branches that implement the functionality.

2020-09-14 16:22 UTC, Tompoudurans commented
I have rebased this branch

2020-09-15 13:35 UTC, drvinceknight requested changes

2020-09-15 13:35 UTC, drvinceknight commented on README.md
> +
Can we add some bullet points / sentences here about what software is required to follow the instructions below.

2020-09-16 10:43 UTC, drvinceknight requested changes

2020-09-16 10:43 UTC, drvinceknight commented on README.md
> +
```suggestion
### Installation

#### Basic software requirements

To install, the following is assumed to be available:

- Python 3.7 or 3.8 (the software might work on other versions but it is only tested on 3.7 or 3.8).
- A recent version of git.

If those are not available please get in touch with the maintainer for alternative ways of installing.

#### Virtual environment

It is recommended to run the software using a Python virtual environment (this ensures that different dependencies are isolated).

To setup the environment, run the following in a command line tool:

    $ python -m venv data-explore

Once the virtual environment is created, it needs to be activated with the following commands:

On Windows, run:

    C:\> data-explore\Scripts\activate.bat

On unix (linux or OS X):

    source data-explore/bin/activate

#### Installation

The following commands will download and install the software

    $ git clone https://github.com/Tompoudurans/data-explore
    $ cd data-explore
    $ python setup.py develop


```

2020-09-16 15:39 UTC, drvinceknight requested changes

2020-09-16 15:39 UTC, drvinceknight commented on README.md
> +
```suggestion


To confirm installation run the following:

    $ python -m dataexplorer --help
```

2020-09-16 17:27 UTC, drvinceknight requested changes
Hadn't realised your markdown syntax wasn't quite right here. Have fixed that as well in my suggestion. (The installation command you wrote would give an error.)

2020-09-16 17:27 UTC, drvinceknight commented on README.md
> +  `$  python -m pytest -p no:logging`
```suggestion
The tool is tested using the Python testing framework purest. To install pytest:

    $ python -m pip install pytest
    
To run the tests:    

    $  python -m pytest -p no:logging

```

2020-09-17 07:54 UTC, Tompoudurans commented
i feel i should remove 
`### Required softwares

To be able to install the software, it is necessary first to have a version of git (any version)
as well as a version of python 3.7 or 3.8 (this software has not been tested for further versions).
Also its is important that pip is installed.`

as there is `#### Basic software requirements`  later on in the read me file

2020-09-18 09:59 UTC, drvinceknight commented on README.md
> +Also its is important that pip is installed.
```suggestion
```

2020-09-18 10:00 UTC, drvinceknight commented
> i feel i should remove

Yeah absolutely I thought that had been removed.

2020-09-18 10:31 UTC, merged